import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Sidebars for the docs app. `autogenerated` pulls every file under
 * docs/ into the sidebar automatically — add MD files and they appear.
 * Move to a hand-maintained structure once the information architecture
 * demands it.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
